"""Add autogenerated agency id

Revision ID: 6adf9d894180
Revises: 7fc6502f1fa3
Create Date: 2025-10-20 16:20:44.081736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adf9d894180'
down_revision: Union[str, None] = '7fc6502f1fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    CREATE SEQUENCE agencies_agency_id START WITH 23191;
    """)

    op.execute("""
    ALTER TABLE agencies ALTER COLUMN agency_id SET DEFAULT nextval('agencies_agency_id');
    """)


def downgrade() -> None:
    pass
